### ISSUE TITLE
/* Invalid asset path */

### ISSUE THREAD

**Issue by marinaprec** [Adyen/adyen-components-js-sample-code#10]
Hi,

I am using dropin in my web, but when i draw my card form, i can´t write number card because the text /* Invalid asset path */ in inside:

![imagen](https://user-images.githubusercontent.com/58332885/70125281-d42ea480-1676-11ea-906e-fbcf74158386.png)

Could somebody help me?

Thanks in advantage.

**Comment by marcperez** [comment]
Hi @marinaprec,

I would suggest contacting our support team: https://support.adyen.com/

In the meantime, I'd recommend you to double check the [documentation regarding our Drop-in integration](https://docs.adyen.com/checkout/drop-in-web#step-2-add-drop-in), specially the `environment` (`test`/`live`) and the `originKey` properties (not to be confused with the API Key, check [How to get an origin key](https://docs.adyen.com/user-management/how-to-get-an-origin-key)).
