### ISSUE TITLE
[BUG] onReady() is not executing on version 3.3.0

### ISSUE THREAD

**Issue by emidev98** [Adyen/adyen-components-js-sample-code#11]
Dear Adyen team, 

I read the documentation and the **onReady()** callback is not called when the component is initialized. [Drop in web](https://docs.adyen.com/checkout/drop-in-web), thanks!

**Comment by marcperez** [comment]
Hi @emidev98,

Thanks for your message. The issue regarding the `onReady` event will be fixed in our next release (`3.4.0`). Please, keep an eye on our [release notes page](https://docs.adyen.com/checkout/components-drop-in-release-notes). Thanks!
