### ISSUE TITLE
/payment

### ISSUE THREAD

**Issue by marinaprec** [Adyen/adyen-components-js-sample-code#13]
Hi, 
I am using dropin and i am trying to make a payment with request /payment, but I receive an error, and I dont Know what is wrong. I tried with this two reques

Both ot them have headers:

The response is:

701 Service null not present

Thanks in advance

**Comment by marcperez** [comment]
Hi @marinaprec,

The endpoint you are looking for is called `/payments` (with an `s`).

https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v51/payments

If you have any other question, please contact our [support team](https://support.adyen.com/). 

Also, please do not share publicly your account information.

Thanks

**Comment by marinaprec** [comment]
Thanks!
 I have a doubt, it is the right way to ask question about the behavior about adyen?

Or maybe I should use another forum.

Thanks

**Comment by marcperez** [comment]
Hi @marinaprec, for future questions about our integrations, I would recommend you contacting us directly in our [support channels](https://support.adyen.com/).

Thanks!
