### ISSUE TITLE
DropIn Pay Button text configuration is not working

### ISSUE THREAD

**Issue by ashifli-x** [Adyen/adyen-components-js-sample-code#14]
When I try to add a custom text value for the Pay Button using the documentation method for placeholders, the "payButton" value does not seem to take effect. even though every other placeholder values work and the changes show up

**Comment by marcperez** [comment]
Hi @ashifli-x,

Please check the [documentation on how to customize the localization strings](https://docs.adyen.com/checkout/components-web/localization-components#customize-localization).

If the problem persists or you have any other question about our integrations, please contact our [support team](https://support.adyen.com/).
