### ISSUE TITLE
What browsers this web component support?

### ISSUE THREAD

**Issue by gssohi** [Adyen/adyen-components-js-sample-code#2]
Can you please provide the details of what all the browsers web component support

**Comment by marcperez** [comment]
On Adyen Components JS we currently support >=IE10, Firefox (Desktop) and Chrome and Safari (All platforms).

Please be aware this repository is just intended as a sample code, and it might use features not available on all browsers.

If you have any issue with a particular browser, please refer to our [support page](https://support.adyen.com/).

**Comment by gssohi** [comment]
Thanks for your quick response, does it support edge browser?

**Comment by marcperez** [comment]
Yes, we do support Edge.
