### ISSUE TITLE
AdyenCheckout as a NPM-package

### ISSUE THREAD

**Issue by josefnorlin** [Adyen/adyen-components-js-sample-code#21]
Hi Adyen,

I like working with your Web Components in our project. However, it would help us if we could have the Adyen Checkout JavaScript file and CSS as an NPM-package.

Instead of having to import these on all our pages in our Buy Flow:
<script src="https://checkoutshopper-live.adyen.com/checkoutshopper/sdk/3.4.0/adyen.js"></script>
<link rel="stylesheet" href="https://checkoutshopper-live.adyen.com/checkoutshopper/sdk/3.4.0/adyen.css"/>

An NPM-package would allow us to not import your components on all our parts of our PWA, as well as making it easier for us to be up to date with versions.

Sincerely yours,
Josef

**Comment by marcperez** [comment]
Hi @josefnorlin 

Thanks for raising this, and our apologies for the delay on our response. 
We recently released our library as an NPM package, you can find it here: https://www.npmjs.com/package/@adyen/adyen-web We hope this helps you with your integration!

Best,
Marc

**Comment by josefnorlin** [comment]
Awesome! Thank you!

**Comment by josefnorlin** [comment]
> Hi @josefnorlin
> 
> Thanks for raising this, and our apologies for the delay on our response.
> We recently released our library as an NPM package, you can find it here: https://www.npmjs.com/package/@adyen/adyen-web We hope this helps you with your integration!
> 
> Best,
> Marc

Awesome, Thank you! This is exactly what we needed!
