### ISSUE TITLE
brands array only detects amex,mc,visa (default values)

### ISSUE THREAD

**Issue by cduque89** [Adyen/adyen-components-js-sample-code#23]
**Describe the bug**
We want to be able to detect more than the default amex, visa, mc in our onBrand callback. 

Everytime we use a card that's not from one of these 3 providers it's detected as 'card'. For example if we configure our component with a brands array that contains cup (China Union Pay) and we try to use one of the test data cards provided in the Adyen docs the onBrand callback will give us 'card' instead of 'cup' (same for all other card providers, we tested all of them individually).

**To Reproduce**
1. Create a component with the following config:

```
new AdyenCheckout({
        locale,
        originKey,
        loadingContext: 'https://checkoutshopper-test.adyen.com/checkoutshopper/',
      })
        .create('securedfields', {
          type: 'scheme',
          brands: ['visa', 'cup'],
          onChange,
          onError,
          onBrand,
          onFieldValid,
          styles: {
            base: {
              color: 'black',
              fontSize: '18px',
              background: '#EDEDED',
              padding: '0 20px',
            },
          },
        })
```

2. Add the onBrand callback as follows:
```  
const onBrand = ({ brand, brandImageUrl }) => {
    console.log(brand, brandImageUrl);
  };
```

3. Check the browser console for the brand and brandImageUrl when using a 'visa' test card all works as expected.

4. Check the browser console for the brand and brandImageUrl when using a 'cup' test card the brand variable value is 'card' and it should be 'cup'.

**Expected behavior**
We use any Adyen supported brand card and the onBrand callback returns the correct brand instead of just 'card'.

**Desktop (please complete the following information):**
 - OS: [MacOS X Catalina, Windows 10]
 - Browser [chrome, firefox]
 - Version [latest version for all browsers]

**Comment by marcperez** [comment]
Hi @cduque89 

Thanks for raising this! This issue seems to be already solved on versions 3.6.0 or greater. You can see this and other release notes here: https://docs.adyen.com/checkout/release-notes#mar-2nd-2020
Hope this solves your issue.

Best,
Marc
