### ISSUE TITLE
AdyenDropIn [Violation] 'setTimeout'

### ISSUE THREAD

**Issue by flaviomurilo-capitani** [Adyen/adyen-components-js-sample-code#24]
CODE:

![image](https://user-images.githubusercontent.com/63069251/94190139-17663800-fe82-11ea-9258-c7576c85f7c6.png)

RESULT:

![image](https://user-images.githubusercontent.com/63069251/94190198-2e0c8f00-fe82-11ea-9cf3-2b0e3e809e20.png)

**Comment by flaviomurilo-capitani** [comment]
TEXT CODE:

<link rel="stylesheet" href="https://checkoutshopper-test.adyen.com/checkoutshopper/sdk/3.11.0/adyen.css">

<section class="container pt-5 pb-5">
    <div class="container container--full-width">
        <div class="main">
            <div class="checkout-container">

                <div class="payment-method">
                    <div id="dropin-container">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script src="https://checkoutshopper-test.adyen.com/checkoutshopper/sdk/3.13.0/adyen.js"></script>
<script type="text/javascript">
    const configuration = {
        environment: "test",
        originKey: "pub.v2.8215689121471259.aHR0cDovL2xvY2FsaG9zdDo1MTk2Mg.wnKUoNLvl5o6eN7c9mNs3yjfQc4pV8BnPEBEe_O2gx4",
        paymentMethodsResponse: JSON.parse('[{"details":[{"key":"number","type":"text"},{"key":"expiryMonth","type":"text"},{"key":"expiryYear","type":"text"},{"key":"cvc","type":"text"},{"key":"holderName","optional":true,"type":"text"}],"name":"Cartão de crédito","type":"scheme","brands":["mc","visa","elo","amex","hipercard","maestro","diners","hiper"]}]'),
        removePaymentMethods: ['paysafecard', 'c_cash']
    };

    console.log(configuration.environment);
    console.log(configuration.originKey);
    console.log(configuration.paymentMethodsResponse);

    const checkout = new AdyenCheckout(configuration);

    const dropin = checkout
        .create('dropin', {
            onSelect: activeComponent => {
                console.log('1');
                //updateStateContainer(activeComponent.data);
            },
            onChange: state => {
                console.log('2');
                //updateStateContainer(state); // Demo purposes only
            },
            onSubmit: (state, component) => {
                console.log('3');
                // state.data;
                // state.isValid;
                //makePayment(state.data);
            }
        })
        .mount('#dropin-container');
</script>

**Comment by flaviomurilo-capitani** [comment]
TEXT CODE

> <link rel="stylesheet" href="https://checkoutshopper-test.adyen.com/checkoutshopper/sdk/3.11.0/adyen.css">

<section class="container pt-5 pb-5">
    <div class="container container--full-width">
        <div class="main">
            <div class="checkout-container">

                <div class="payment-method">
                    <div id="dropin-container">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script src="https://checkoutshopper-test.adyen.com/checkoutshopper/sdk/3.13.0/adyen.js"></script>
<script type="text/javascript">
    const configuration = {
        environment: "test",
        originKey: "pub.v2.8215689121471259.aHR0cDovL2xvY2FsaG9zdDo1MTk2Mg.wnKUoNLvl5o6eN7c9mNs3yjfQc4pV8BnPEBEe_O2gx4",
        paymentMethodsResponse: JSON.parse('[{"details":[{"key":"number","type":"text"},{"key":"expiryMonth","type":"text"},{"key":"expiryYear","type":"text"},{"key":"cvc","type":"text"},{"key":"holderName","optional":true,"type":"text"}],"name":"Cartão de crédito","type":"scheme","brands":["mc","visa","elo","amex","hipercard","maestro","diners","hiper"]}]'),
        removePaymentMethods: ['paysafecard', 'c_cash']
    };

    console.log(configuration.environment);
    console.log(configuration.originKey);
    console.log(configuration.paymentMethodsResponse);

    const checkout = new AdyenCheckout(configuration);

    const dropin = checkout
        .create('dropin', {
            onSelect: activeComponent => {
                console.log('1');
                //updateStateContainer(activeComponent.data);
            },
            onChange: state => {
                console.log('2');
                //updateStateContainer(state); // Demo purposes only
            },
            onSubmit: (state, component) => {
                console.log('3');
                // state.data;
                // state.isValid;
                //makePayment(state.data);
            }
        })
        .mount('#dropin-container');
</script>

**Comment by flaviomurilo-capitani** [comment]
TEXT CODE


[AdyenDropInWeb.zip](https://github.com/Adyen/adyen-components-js-sample-code/files/5278704/AdyenDropInWeb.zip)

**Comment by pabloai** [comment]
Hi @flaviomurilo-capitani,

It seems you're not passing the whole response from the `/paymentMethods` endpoint, only the `paymentMethods` object from that response. Passing the whole response should solve the issue.

Let us know if there's anything else we can help with. Cheers!

**Comment by flaviomurilo-capitani** [comment]
I dont manipuling the adyen response from payment methods, it´s get from Adyen Itself.

c# code returning Adyen.Model.Checkout.PaymentMethodsResponse from Nuget Adyen Package

![image](https://user-images.githubusercontent.com/63069251/94432495-3b20cb00-016d-11eb-931a-f597b627ed73.png)

![image](https://user-images.githubusercontent.com/63069251/94432317-fd23a700-016c-11eb-8819-2bdb2b23d3e5.png)

**Comment by pabloai** [comment]
Ah, I see. Thanks for adding more clarity!

I already mentioned this to one of the devs in charge of the [Adyen Dotnet API library](https://github.com/Adyen/adyen-dotnet-api-library/).

What you can do for now is to use the [ToJson method](https://github.com/Adyen/adyen-dotnet-api-library/blob/499c639353926d3397a492d0a574cda5ec81d25b/Adyen/Model/Checkout/PaymentMethodsResponse.cs#L103) like this:
```
string paymentMethodsJson = paymentMethodsResponse.ToJson();
```
And then pass the whole response back to the frontend as a JSON string.

I hope this helps.
Feel free to send more questions or proposals. Cheers!
