### ISSUE TITLE
Missing /api/clientKeys

### ISSUE THREAD

**Issue by jopasb** [Adyen/adyen-components-js-sample-code#26]
Hi,
when I start application with nodejs I get error Error: Cannot find module './api/clientKeys'
when I start php app, I get error require(api/clientKeys.php): failed to open stream: No such file or directory in /
Could you please investigate?
Regards,
Josip.

**Comment by marcperez** [comment]
Hi @jopasb,

Thanks for opening this issue! It should be fixed now, but feel free to open a new issue if there's any other problem.
