### ISSUE TITLE
Usage with React Native

### ISSUE THREAD

**Issue by asgvard** [Adyen/adyen-components-js-sample-code#4]
Hi!

I have seen that there was an Issue opened for this in the `adyen-cse-web` repo in 2017, but it was closed as "not an issue".
I am not sure in which repo should I open this, but currently we are developing an application on React Native and we are not sure which implementation should we pick to integrate with Adyen.
I have seen that you provide [API Only](https://docs.adyen.com/checkout/api-only) way, but still it only provides us with either Web components, or native components for Android or iOS.
The problem is that in React Native we cannot use HTML ones. Also for Native ones we have to create some wrappers, as seen in this [3rd party library](https://github.com/dmitry-blackwave/adyen-react-native) that is still missing a lot of features and I'm not sure if it's reliable enough.
So the issue is that we don't have good first class support for React Native (which is very popular framework and a lot of people doing apps using it). Is there any plan for Adyen to add support for custom UI elements for React Native to be able to do payments? Or if not, which exact way of implementing it would you recommend assuming neither Web HTML elements nor native components would work out of the box for React Native?

Thank you,
Dmitriy

**Comment by marcperez** [comment]
Hi @asgvard and our apologies for the delay on the response.

At this moment there are no plans on a specific React Native solution. We would recommend you to use our native mobile libraries ([iOS](https://docs.adyen.com/checkout/ios/components) and [Android](https://docs.adyen.com/checkout/android)).

If you have any other question about our integrations, please contact our [support team](https://support.adyen.com/).

Thanks!
