### ISSUE TITLE
Does this support billing address

### ISSUE THREAD

**Issue by gssohi** [Adyen/adyen-components-js-sample-code#7]
Hi
We want to send a billing address along with the credit card details. Does this component support billing address or can we extend this to support billing address?

**Comment by marcperez** [comment]
Hi @gagandeepsinghsohi 

At this moment we don't provide a billing address form on our Card Component. However you can collect that data in your own form and send it in the `/payments` API call. You can find more information [here](https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v51/payments__reqParam_billingAddress).
