### ISSUE TITLE
Drop In new AdyenCheckout, paymentMethodsResponse 

### ISSUE THREAD

**Issue by marinaprec** [Adyen/adyen-components-js-sample-code#8]
Hello,

I am using dropin in my web, but I can not paint the response of the /paymentMethods with js.
This is the issue, I have the response in js, likie this:

const paymentMethodsResponse = "{'groups':[{'name':'Credit Card','types':['visa','mc','amex','maestro','diners','discover']}],'paymentMethods':[{'brands':['visa','mc','amex','maestro','diners','discover'],'details':[{'key':'encryptedCardNumber','type':'cardToken'},{'key':'encryptedSecurityCode','type':'cardToken'},{'key':'encryptedExpiryMonth','type':'cardToken'},{'key':'encryptedExpiryYear','type':'cardToken'},{'key':'holderName','optional':true,'type':'text'}],'name':'Credit Card','type':'scheme'},{'name':'PayPal','supportsRecurring':true,'type':'paypal'},{'details':[{'key':'sepa.ownerName','type':'text'},{'key':'sepa.ibanNumber','type':'text'}],'name':'SEPA Direct Debit','supportsRecurring':true,'type':'sepadirectdebit'},{'name':'SEPA Bank Transfer','supportsRecurring':true,'type':'bankTransfer_IBAN'}]}";

then, I create an instance :

    // 1. Create an instance of AdyenCheckout

const checkout = new AdyenCheckout({
locale:'es-ES',
environment: 'test',
originKey: 'my key, // Mandatory. originKey from Costumer Area
paymentMethodsResponse: paymentMethodsResponse

});
And after that , I mount the rest:

// 2. Create and mount the Component
const dropin = checkout.create('dropin').mount('#dropin-container');
// 2. Create and mount the Component
const card = checkout .create('card').mount('#card-container');

But I don´t get draw my payment methods.

What am I doing wrong?

**Comment by marcperez** [comment]
Hi @marinaprec,

I think in this case it could be caused by the `paymentMethodsResponse` being a string, instead of an object. Could you try removing the `"` quotes? As in:

```js
const paymentMethodsResponse = {'groups':[{'name':'Credit Card','types':['visa','mc','amex','maestro','diners','discover']}],'paymentMethods':[{'brands':['visa','mc','amex','maestro','diners','discover'],'details':[{'key':'encryptedCardNumber','type':'cardToken'},{'key':'encryptedSecurityCode','type':'cardToken'},{'key':'encryptedExpiryMonth','type':'cardToken'},{'key':'encryptedExpiryYear','type':'cardToken'},{'key':'holderName','optional':true,'type':'text'}],'name':'Credit Card','type':'scheme'},{'name':'PayPal','supportsRecurring':true,'type':'paypal'},{'details':[{'key':'sepa.ownerName','type':'text'},{'key':'sepa.ibanNumber','type':'text'}],'name':'SEPA Direct Debit','supportsRecurring':true,'type':'sepadirectdebit'},{'name':'SEPA Bank Transfer','supportsRecurring':true,'type':'bankTransfer_IBAN'}]};
```

If you have any other question about our integrations, please contact our [support team](https://support.adyen.com/).

**Comment by marinaprec** [comment]
![imagen](https://user-images.githubusercontent.com/58332885/69882443-6d089d00-12d0-11ea-8000-8c40603a7150.png)
 This is my source, you can see that paymentMethosResponse is a JSON, but when checkout in instancied there is nothing in paymentsMethods:

![imagen](https://user-images.githubusercontent.com/58332885/69882665-38e1ac00-12d1-11ea-9be9-5cc704337eaf.png)
